name: 🧪 CI Checks

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - 'backend/**'
      - '.github/workflows/ci.yml'
  workflow_dispatch:
  workflow_call:

jobs:
  lint-frontend:
    name: Lint Frontend
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: 'package-lock.json'
    
    - name: Install Dependencies
      run: npm ci
    
    - name: Run Linting
      run: npm run lint:frontend

  lint-and-test-backend:
    name: Lint and Test Backend
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: 'package-lock.json'
    
    - name: Install Dependencies
      run: npm ci
    
    - name: Run Linting
      run: npm run lint:backend
    
    - name: Run Tests
      run: npm run test:backend

  ci-passed:
    name: All CI Checks Passed
    needs: [lint-frontend, lint-and-test-backend]
    runs-on: ubuntu-latest
    steps:
      - name: CI Check Summary
        run: echo "All CI checks have passed! ✓" 